name: FileSearch

on: [push]

jobs:
  file_presence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Check file presence"
        uses: JJ/files-present-action@releases/v1
        with:
          files: "pom.xml xxx"
