name: TestHello

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Tell name
        uses: Mykyta/hello-world-javascript-action@3
        id: hello
        with:
          name: 'Nick'
