# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v7
      with:
        servers: '[{ "id": "nexus-server", "username": "admin", "password": "BJzKWEv3KGw@Rj4r_!MT" }]'
        mirrors: '[{ "id": "nexus-server", "mirrorOf": "external:*", "url": "https://06c0eb745b0b.ngrok.io/repository/dev/" }]'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
